version: '3.8'
services:

  db:
    image: postgres:15
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
    #expose:
    #  - '5432'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  django:
    build: ./django
    image: django
    container_name: django
    expose:
      - '8080'
    volumes:
      - ./src:/code
      - ./django/uwsgi:/etc/uwsgi
    depends_on:
      - db

  web:
    image: nginx:1.23.2
    container_name: nginx
    volumes:
      - ./web/conf:/etc/nginx/conf.d
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    ports:
      - '80:80'
    depends_on:
      - django